production_url : 'https://diogomonica.com'

"theme-bootstrap-3":
  "use" : "theme"

posts :
  summary_lines : 5
  "sort" : ["date", "desc"]

plugins:
  sitemap:
    file_name: sitemap.xml
    changefreq: daily
    priority: 0.7
